// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMT.Persistence.SMTConfiguration;

#nullable disable

namespace SMT.Persistence.Migrations
{
    [DbContext(typeof(SMTDBContext))]
    [Migration("20260404090038_CreateProfileUser")]
    partial class CreateProfileUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMT.Domain.Models.MonthColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PaidTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("QuarterId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TaxPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuarterId");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("SMT.Domain.Models.Quarter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("YearID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("YearID");

                    b.ToTable("Quarters");
                });

            modelBuilder.Entity("SMT.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMT.Domain.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("IpRegistrationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SMT.Domain.Models.Year", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameTable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("TotalForQuarter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("SMT.Domain.Models.MonthColumn", b =>
                {
                    b.HasOne("SMT.Domain.Models.Quarter", "Quarter")
                        .WithMany("Columns")
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("SMT.Domain.Models.Quarter", b =>
                {
                    b.HasOne("SMT.Domain.Models.Year", "Year")
                        .WithMany("Quarters")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("SMT.Domain.Models.UserProfile", b =>
                {
                    b.HasOne("SMT.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMT.Domain.Models.Year", b =>
                {
                    b.HasOne("SMT.Domain.Models.User", "User")
                        .WithMany("Years")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMT.Domain.Models.Quarter", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SMT.Domain.Models.User", b =>
                {
                    b.Navigation("Years");
                });

            modelBuilder.Entity("SMT.Domain.Models.Year", b =>
                {
                    b.Navigation("Quarters");
                });
#pragma warning restore 612, 618
        }
    }
}
